export default {
  LOAD_MOVIES: 'LOAD_MOVIES',
  LOAD_MOVIE: 'LOAD_MOVIE',

  LOAD_WISHLIST: 'LOAD_WISHLIST',
  ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
  DELETE_FROM_WISHLIST: 'DELETE_FROM_WISHLIST',

  LOAD_MOVIES_ERROR: 'LOAD_MOVIES_ERROR',
  LOAD_MOVIE_ERROR: 'LOAD_MOVIE_ERROR',
};
